security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    admin_entity:
      entity:
        class: AlAya\Common\Entity\Agent
        property: "username"
    student_entity:
      entity:
        class: AlAya\Common\Entity\Student
        property: "email"

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    admin:
      pattern: ^/admin
      user_checker: AlAya\Agent\SecurityBundle\Security\adminChecker
      lazy: true
      provider: admin_entity
      form_login:
        login_path: AgentSecurityBundle_Login
        check_path: AgentSecurityBundle_Login
        default_target_path: "AgentDashboardBundle_Index"
        username_parameter: username
        password_parameter: password
      logout:
        path: AgentSecurityBundle_LogOut
        target: AgentSecurityBundle_Login

        #target: "/{_locale}/provider"

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#the-firewall

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
  access_control:
    # admin
    #- { host: ^bo\.(%project.host%)$, path: ^/login, roles: PUBLIC_ACCESS }
    #- { host: ^bo\.(%project.host%)$, path: ^/, roles: IS_AUTHENTICATED_FULLY }
    - {  path: ^/admin/.*/login, roles: PUBLIC_ACCESS }
    - {  path: ^/admin/.*/, roles:  [IS_AUTHENTICATED_FULLY] }
    - {  path: ^/login, roles: PUBLIC_ACCESS }
    - {  path: ^/register, roles: PUBLIC_ACCESS }
    - {  path: ^/api/loadFormulats, roles: PUBLIC_ACCESS }
    - {  path: ^/api/addMessage, roles: PUBLIC_ACCESS }
    - {  path: ^/invitation, roles: PUBLIC_ACCESS }
    - {  path : ^/checkout, roles: PUBLIC_ACCESS }
    - {  path: ^/, roles: [IS_AUTHENTICATED_FULLY] }
    

    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      # By default, password hashers are resource intensive and take time. This is
      # important to generate secure password hashes. In tests however, secure hashes
      # are not important, waste resources and increase test times. The following
      # reduces the work factor to the lowest possible values.
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
