framework:
    workflows:
        prestation :
            type: "state_machine"  
            marking_store:
                type: "method"
                property: "status"
            supports:
                - AlAya\Common\Entity\Prestation
            places:
                - brouillon
                - forfait expiré
                - en attendant le paiement
                - en cours
                - pause
                - clôturée	
            transitions:
                facturer_1 :
                    from: brouillon
                    to: en attendant le paiement
                    metadata: 
                        description: "Rechercher le forfait"
                        color : "btn btn-dark"
                facturer_2 :
                    from: forfait expiré
                    to: en attendant le paiement
                    metadata: 
                        description: "Rechercher le forfait"
                        color : "btn btn-dark"
                facturer_3 :
                    from: forfait expiré
                    to: clôturée
                    metadata: 
                        description: "Clôturer"
                        color : "btn btn-success"
                en_cours :
                    from: en attendant le paiement
                    to: en cours
                    metadata: 
                        description: "Valider le paiement"
                        color : "btn btn-success"
                en_cours_2 :
                    from: pause
                    to: en cours
                    metadata: 
                        description: "Reprise"
                        color : "btn btn-success"
                pause :
                    from: en cours
                    to: pause
                    metadata: 
                        description: "Pause"
                        color : "btn btn-primary"
                cloturer :
                    from: en attendant le paiement
                    to : clôturée
                    metadata: 
                        description: "Clôturer"
                        color : "btn btn-info"
                cloturer_2 :
                    from: en cours
                    to : clôturée
                    metadata: 
                        description: "Clôturer"
                        color : "btn btn-success"
