#Gestion des Utilisateurs
back_agent_index:
  label: Voir les utilisateurs
  module: Gestion des Utilisateurs

back_agent_edit:
  label: Modifier un utilisateur
  module: Gestion des Utilisateurs

back_agent_add:
  label: Ajouter un utilisateur
  module: Gestion des Utilisateurs

back_agent_set_params:
  label: Paramétrages
  module: Gestion des Utilisateurs

#Gestion des rôles
back_role_index:
  label: Voir les rôles
  module: Gestion des rôles

back_role_edit:
  label: Modifier un rôle
  module: Gestion des rôles

back_role_add:
  label: Ajouter un rôle
  module: Gestion des rôles

#Gestion des groupes
back_group_index:
  label: Voir les groupes
  module: Gestion des groupes

back_group_show:
  label: Détails d’un groupe
  module: Gestion des groupes

#Gestion des étudiants
back_student_index:
  label: Voir les étudiants
  module: Gestion des étudiants

back_student_new:
  label: Ajouter un étudiant
  module: Gestion des étudiants

back_student_edit:
  label: Modifier un étudiant
  module: Gestion des étudiants

#Gestion des sessions (prestations)
back_prestation_index:
  label: Voir les prestations
  module: Gestion des prestation

back_prestation_create:
  label: Créer une prestation
  module: Gestion des prestation

back_prestation_show:
  label: Modifier une prestation
  module: Gestion des prestation

back_prestation_pay:
  label: Paiement de la prestation
  module: Gestion des prestation

#Gestion des paiements
payement_index:
  label: Voir les paiements
  module: Gestion des paiements

back_payement_add:
  label: Ajouter un paiement
  module: Gestion des paiements

back_payement_download_invoice:
  label: Télécharger la facture
  module: Gestion des paiements

#Reporting
back_reporting_index:
  label: Reporting rémunérations
  module: Reporting

back_programme_index :
  label: Consulter les programmes
  module: Gestion des programmes